name: Publish docs to GitHub Pages

on:
  push:
    branches: [ "main" ]
    
permissions:
  pages: write
  id-token: write

jobs:
  build-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Set up GitHub Pages
      uses: actions/configure-pages@v3
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Restore dotnet projects
      run: dotnet restore
    - name: Build
      run: dotnet build ./FSharp.AspNetCore.WebAppBuilder/FSharp.AspNetCore.WebAppBuilder.fsproj -c Release -f net7.0
    - name: Copy readme to docs folder
      run: cp README.md docs/index.md
    - name: Build docs
      run: |
        dotnet fsdocs build \
          --output ./out \
          --properties Configuration=Release TargetFramework=net7.0 \
          --parameters \
            fsdocs-license-link https://github.com/brianrourkeboll/FSharp.AspNetCore.WebAppBuilder/blob/main/LICENSE.md \
            fsdocs-release-notes-link https://github.com/brianrourkeboll/FSharp.AspNetCore.WebAppBuilder/releases
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './out'
  
  publish-docs:

    needs: build-docs

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
